import type { Bulletin, ClinicalDepartment, Department, KnowledgeArticle, StaffMember } from "@/types/portal";

/**
 * Local mock dataset for the operations portal.
 *
 * Single source of truth for UI work. Each export is replaced by a Supabase
 * query returning the same shapes when the backend lands. Timestamps are
 * hard-coded ISO strings rather than `Date.now()` so server and client render
 * identically.
 *
 * Markdown bodies use the conventions understood by `components/MarkdownReader`:
 * `##` / `###` headings (they populate the article table of contents), pipe
 * tables, and `> [!warning]` style clinical callouts.
 */

export const KNOWLEDGE_ARTICLES: readonly KnowledgeArticle[] = [
  {
    id: "3f2b9c14-8a7d-4e51-9b0c-6d1e2f4a7c88",
    title: "Canine Parvovirus Isolation Protocol",
    slug: "canine-parvovirus-isolation-protocol",
    departments: ["ICU", "ER"],
    status: "published",
    updated_at: "2026-09-12T16:40:00.000Z",
    author_name: "Trevor Lindqvist, ICU Technician II",
    body_markdown: [
      "**Owner:** Infectious Disease Control Committee · **Review cycle:** Every 6 months · **Applies to:** All clinical staff entering the isolation ward",
      "",
      "## Purpose",
      "",
      "Prevent nosocomial transmission of canine parvovirus (CPV-2) between hospitalized patients, boarding guests, and the general lobby population. Any dog presenting with acute hemorrhagic diarrhea, profound lethargy, or an unverified vaccine history is treated as a **suspected parvo case** until a SNAP test is negative.",
      "",
      "## Immediate actions on suspicion",
      "",
      "1. Do not let the patient touch the lobby floor. Move directly to the side-door intake bay.",
      "2. Notify the attending DVM and place an isolation flag on the cage card.",
      "3. Run an in-house SNAP Parvo test in the isolation prep area only — never at the central treatment table.",
      "4. Don full PPE before handling: gown, gloves, shoe covers, and a dedicated isolation stethoscope.",
      "5. Log the intake in the isolation registry with patient name, time, and the room number assigned.",
      "",
      "## Ward assignment",
      "",
      "Isolation bays are single-occupancy. Cohorting two confirmed CPV patients is permitted **only** when both are confirmed positive by the same in-house test and the ward is otherwise full; document the decision and the approving DVM in the registry.",
      "",
      "> [!warning] A patient is not cleared from isolation until two consecutive negative in-house SNAP tests are documented 24 hours apart, or a fecal PCR is negative. Discharge before that window is a reportable protocol deviation.",
      "",
      "## Barrier and disinfection standards",
      "",
      "- Parvovirus is non-enveloped and resistant to alcohol and quaternary ammonium alone.",
      "- Use accelerated hydrogen peroxide or a 1:32 bleach dilution with a **10 minute** wet contact time.",
      "- Change gowns and gloves between every patient, even within the same bay.",
      "- Dedicated supplies stay in the ward: thermometer, clippers, food bowls, and mop head.",
      "",
      "| Surface | Agent | Wet contact time |",
      "| --- | --- | --- |",
      "| Stainless cage | Accelerated hydrogen peroxide | 5 minutes |",
      "| Floors and drains | 1:32 bleach | 10 minutes |",
      "| Stethoscope and thermometers | Accelerated hydrogen peroxide wipe | 2 minutes |",
      "| Laundry | Standard wash, 60 °C minimum | Full cycle |",
      "",
      "## Client communication",
      "",
      "CSR staff should set expectations at intake: isolation patients are visited by staff only, and the client receives one scheduled phone update per shift. Do not promise a discharge date before the second negative test.",
      "",
      "### Documentation",
      "",
      "Every entry into the isolation ward — staff, patient, or equipment — gets a timestamped row in the registry sheet. The ward is audited weekly by the Safety Officer.",
    ].join("\n"),
  },
  {
    id: "9c47a2e0-51b8-4f3a-8d92-77e5c1b0a3d6",
    title: "Code Blue: RECOVER Resuscitation Team Roles",
    slug: "code-blue-recover-resuscitation-roles",
    departments: ["ER", "ICU", "Cardiology"],
    status: "published",
    updated_at: "2026-08-29T19:15:00.000Z",
    author_name: "Dr. Maya Okonkwo, Lead Emergency Clinician",
    body_markdown: [
      "**Owner:** Emergency & Critical Care · **Reference:** RECOVER 2012 CPR guidelines, hospital-internal adaptation",
      "",
      "## Activation",
      "",
      "Any team member who identifies an unresponsive patient calls **`Code Blue`** at full volume and starts chest compressions immediately. Do not wait for the DVM. Announcing the code is never a disciplinary matter — a false alarm costs nothing.",
      "",
      "## Assigned roles",
      "",
      "| Role | Filled by | Responsibility |",
      "| --- | --- | --- |",
      "| Team Leader | Attending DVM | Calls the algorithm, doses drugs, owns the record |",
      "| Compressor | Technician | Delivers compressions, rotates every 2 minutes |",
      "| Ventilation | Technician | Intubation and bagging at 10 breaths/min |",
      "| Crash Cart | Technician | Draws drugs, hands them off, restocks after |",
      "| Recorder | CSR or Technician | Time-stamps every dose, shock, and rhythm check |",
      "| Client Liaison | CSR | Retrieves the client, moves them to a consult room |",
      "",
      "## Rhythm checks",
      "",
      "Pause compressions only at **2 minute** intervals to check rhythm and pulse. Keep the pause under 10 seconds. Announce `pausing` before you stop and `resuming` before you restart so the recorder can log it.",
      "",
      "> [!critical] Do not interrupt compressions for intubation or IV access. Those happen during the 2 minute cycle, never as a stand-alone pause.",
      "",
      "## Drug doses",
      "",
      "- **Epinephrine:** 0.01 mg/kg IV, repeat every 3–5 minutes",
      "- **Atropine:** 0.04 mg/kg IV (or 0.08 mg/kg IT on a low-dose epi protocol)",
      "- **Lidocaine:** 2 mg/kg IV bolus if ventricular fibrillation or pulseless VT",
      "- Repeat epinephrine doses are escalated, not equal — follow the team leader's call, not the first syringeful.",
      "",
      "## Defibrillation",
      "",
      "Biphasic, 4–6 J/kg for the first shock on V-fib. Recharge fully between shocks, and clear the table verbally before every discharge.",
      "",
      "### Debrief and restock",
      "",
      "Within the same shift, the team leader convenes a 10 minute debrief covering what went well, what broke down, and whether the crash cart is fully restocked. The recorder's sheet is filed in the patient record and a copy goes to the Safety Officer.",
    ].join("\n"),
  },
  {
    id: "a71c04d8-2f69-4b83-9e57-3c8a1d6f4b20",
    title: "Chemotherapy Extravasation Response",
    slug: "chemotherapy-extravasation-response",
    departments: ["Oncology", "ICU"],
    status: "published",
    updated_at: "2026-09-08T11:25:00.000Z",
    author_name: "Dr. Sofia Almeida, Medical Oncologist",
    body_markdown: [
      "**Owner:** Oncology Service · **Applies to:** Anyone administering or assisting with vesicant chemotherapy",
      "",
      "## Definition and risk",
      "",
      "Extravasation is the inadvertent leakage of a vesicant agent into perivascular or subcutaneous tissue. Doxorubicin, vincristine, and mechlorethamine account for the majority of serious injuries in our caseload.",
      "",
      "> [!critical] Stop the infusion immediately. Do not remove the catheter before aspirating. This is a time-critical injury — tissue damage progresses within the first 30 minutes.",
      "",
      "## Immediate response sequence",
      "",
      "1. Stop the infusion and disconnect the giving set at the port, leaving the catheter in place.",
      "2. Aspirate as much residual drug and fluid as possible through the existing catheter.",
      "3. Mark the perimeter of the affected area with a skin marker and note the time.",
      "4. Notify the attending oncologist and the pharmacy on extension 4359.",
      "5. Apply the agent-specific management below. Cold compresses for anthracyclines, warm compresses for vinca alkaloids.",
      "",
      "| Agent | Compress | Antidote | Monitoring window |",
      "| --- | --- | --- | --- |",
      "| Doxorubicin | Cold, 15 min qid × 48 h | Dexrazoxane within 3 h | 7 days |",
      "| Vincristine | Warm, 15 min qid × 48 h | Hyaluronidase infiltration | 7 days |",
      "| Mechlorethamine | Cold, 15 min qid × 48 h | Sodium thiosulfate 1/6 M | 5 days |",
      "",
      "## Documentation",
      "",
      "- Photograph the site at 0, 24, and 72 hours and attach to the patient record.",
      "- File an incident report the same day regardless of apparent severity.",
      "- Record the agent, concentration, estimated volume, and time to intervention.",
      "",
      "### Follow-up",
      "",
      "The oncology service rechecks the site weekly until the lesion has fully resolved. Ulceration that fails to improve by day 10 is referred for surgical debridement.",
    ].join("\n"),
  },
  {
    id: "1d5b7e94-6c30-4a12-b8f5-9e2d0c7a4b63",
    title: "Client Estimates, Deposits & Payment Plans",
    slug: "client-estimates-deposits-payment-plans",
    departments: ["CSR", "Finance"],
    status: "published",
    updated_at: "2026-09-20T17:30:00.000Z",
    author_name: "Priya Raghunathan, Client Experience Coordinator",
    body_markdown: [
      "**Owner:** Client Experience · **Revision:** September 2026 — deposit thresholds updated",
      "",
      "## When an estimate is required",
      "",
      "Every hospitalized patient, every surgical procedure, and any outpatient visit with a projected total above $250 gets a written estimate before treatment begins. Walk the client through it line by line rather than handing over a printout.",
      "",
      "## Deposit thresholds",
      "",
      "Deposits are collected at the time of admission, before the patient goes to the treatment floor.",
      "",
      "```",
      "Projected estimate       Deposit required",
      "$250  - $750             50% of high-end estimate",
      "$751  - $2,000           $500 flat",
      "$2,001 - $5,000          50% of high-end estimate",
      "over $5,000              60%, plus DVM approval",
      "```",
      "",
      "## Presenting three tiers",
      "",
      "Always present options rather than a single number. Clients who are shown a good / better / best breakdown approve treatment more often and call back to dispute charges less often.",
      "",
      "- **Essential** — stabilizes the patient and addresses the life threat.",
      "- **Recommended** — the diagnostics the DVM actually wants, including imaging.",
      "- **Complete** — adds advanced imaging, extended hospitalization, and specialist referral.",
      "",
      "> [!note] Never decline to present an estimate because you assume the client cannot pay. Present the number; the client decides.",
      "",
      "## Approval and signature",
      "",
      "1. Print two copies; the client signs the hospital copy.",
      "2. Record verbal approvals in the client communication log with a timestamp.",
      "3. Any treatment exceeding the approved high end by more than 15% requires a call to the client **before** the work continues.",
      "",
      "### Escalation",
      "",
      "Disputes over an existing invoice go to the Client Experience Coordinator first, then the Practice Administrator. Front-desk staff should not negotiate balances down at the counter.",
    ].join("\n"),
  },
  {
    id: "b6d1f830-2ac9-4e77-90f1-4a8c3b5d9e21",
    title: "Fear-Free Restraint & Aggressive Patient Handling",
    slug: "fear-free-restraint-aggressive-patient-handling",
    departments: ["ER", "Exotics", "Pain Management/Rehabilitation"],
    status: "draft",
    updated_at: "2026-09-18T14:05:00.000Z",
    author_name: "Dana Whitfield, Facilities & Safety Officer",
    body_markdown: [
      "**Owner:** Safety Committee · **Status:** DRAFT — pending review by the clinical leads. Not yet in force.",
      "",
      "## Why this is being rewritten",
      "",
      "Three staff bites and two cat scratch infections were logged this year, all during routine restraint for blood draws. This draft replaces the older 'scruff and stretch' guidance with a graded, patient-directed approach.",
      "",
      "## Restraint ladder",
      "",
      "Work down the ladder one rung at a time. Never skip rungs because the appointment is running late.",
      "",
      "1. **Low-stress exam room** — pheromone spray, non-slip mat, dimmed lighting, treats on a lick mat.",
      "2. **Towel wrap** for cats and small dogs. Keep the head exposed only as long as the procedure needs.",
      "3. **Basket muzzle** sized to the patient. Avoid gauze-loop muzzles on brachycephalic breeds.",
      "4. **Chemical restraint** — DVM-ordered oral or injectable sedation. Not a last resort; it is a reasonable second rung for a genuinely panicked patient.",
      "5. **Two-person minimum** for any lateral restraint on a patient larger than 15 kg.",
      "",
      "## Warning signs — stop the procedure",
      "",
      "Whale eye, flattened ears, tucked tail, growling, freeze-then-snap, and raised hackles are all stop signals. If you see one, pause, re-evaluate, and consider the next rung of the ladder.",
      "",
      "> [!warning] Restraint is not a contest. If a procedure requires more force than the plan allows, the correct action is to stop, sedate, and reschedule — not to push through.",
      "",
      "## Bite and scratch reporting",
      "",
      "- Wash the wound immediately with soap and running water for 15 minutes.",
      "- Report to the Safety Officer the same day, including the patient record number.",
      "- File an incident form within 24 hours regardless of severity.",
      "- Never apply a bandage over a bite wound without a physician review.",
      "",
      "### Open questions for review",
      "",
      "- Do we stock basket muzzles in all four exam rooms or keep them at the treatment table?",
      "- Should chemical restraint require a second DVM signature for patients already under a pain protocol?",
      "- What is the escalation path when a client refuses sedation and the patient cannot be safely handled?",
    ].join("\n"),
  },
];

export const BULLETINS: readonly Bulletin[] = [
  {
    id: "e8a2c5f1-3b74-4d09-a6c2-5f81b0d4e937",
    title: "Isolation bays at 3 of 4 capacity — intake diversion active through Friday",
    departments: ["ICU", "ER"],
    priority: "urgent",
    linked_sop_id: "3f2b9c14-8a7d-4e51-9b0c-6d1e2f4a7c88",
    created_at: "2026-09-20T21:10:00.000Z",
    author_name: "Dr. Maya Okonkwo, Lead Emergency Clinician",
    body_markdown: [
      "Three of our four isolation bays are occupied with confirmed CPV patients. Two more suspected cases are inbound from the Eastside referral.",
      "",
      "## What changes on shift",
      "",
      "- Suspected parvo cases are stabilized and referred out unless the patient is critical.",
      "- The fourth bay is held for confirmed positives only. No boarding or elective use.",
      "- Cohorting two confirmed positives in bay 4 is authorized **for this week only**; log the decision and the approving DVM in the isolation registry.",
      "- Every intake gets a SNAP test before it touches the treatment floor.",
      "",
      "> [!warning] Accelerated hydrogen peroxide or 1:32 bleach with a full 10 minute wet contact time. Alcohol wipes do nothing to parvo.",
      "",
      "Diversion lifts once two bays are cleared by consecutive negative tests.",
    ].join("\n"),
  },
  {
    id: "d41f8b93-6a20-4c75-8e19-7b5d2c0f6a38",
    title: "Radiology suite 2 offline Tuesday 06:00–10:00 for generator service",
    departments: ["Radiology", "ER"],
    priority: "normal",
    created_at: "2026-09-20T13:05:00.000Z",
    author_name: "Marcus Oyelaran, Diagnostic Imaging Lead",
    body_markdown: [
      "Suite 2 is booked for its annual generator service window on Tuesday. Suite 1 remains fully available for all urgent studies.",
      "",
      "## During the outage",
      "",
      "- All stat radiographs route to suite 1. Expect a 10–15 minute queue at peak.",
      "- CT is unaffected and can absorb the overflow for trauma imaging.",
      "- Scheduled outpatient imaging has been rebooked; no action needed from CSR beyond confirming the new times.",
      "",
      "> [!note] If a case cannot wait for the queue, escalate to the attending DVM and consider point-of-care ultrasound.",
      "",
      "Suite 2 returns to service at 10:00, or earlier if the service window closes ahead of schedule.",
    ].join("\n"),
  },
  {
    id: "4c9e1b70-8d25-4f6b-9a30-2e7c6d1f8b45",
    title: "Updated deposit thresholds take effect Monday",
    departments: ["CSR", "Finance"],
    priority: "pinned",
    linked_sop_id: "1d5b7e94-6c30-4a12-b8f5-9e2d0c7a4b63",
    created_at: "2026-09-18T15:45:00.000Z",
    author_name: "Priya Raghunathan, Client Experience Coordinator",
    body_markdown: [
      "The revised deposit schedule goes live Monday at open. The estimator templates in the practice system are already updated.",
      "",
      "## What is different",
      "",
      "- The flat $500 deposit band now covers estimates from $751 to $2,000 (previously $500–$1,500).",
      "- Estimates over $5,000 require 60% down plus a DVM approval, up from 50%.",
      "- The three-tier presentation is now required for every hospitalization, not just surgical cases.",
      "",
      "## What to do before Monday",
      "",
      "1. Read the linked SOP end to end — it is short and the replacement section is Deposit thresholds.",
      "2. Print the new tiered template for your desk drawer.",
      "3. Flag any open invoice where the old threshold was applied and the patient is still hospitalized.",
      "",
      "Questions to Priya at extension 4021.",
    ].join("\n"),
  },
  {
    id: "7b3f0a26-9c58-4e14-b7d2-8a5f3c9e0d61",
    title: "Controlled substance log audit — September reconciliation closes Friday",
    departments: ["Finance", "ICU"],
    priority: "normal",
    created_at: "2026-09-16T13:20:00.000Z",
    author_name: "Nadia Fournier, Practice Finance Manager",
    body_markdown: [
      "The September controlled substance reconciliation closes Friday at 5:00 PM. Every logged dose must have a matching witness signature before the books close.",
      "",
      "## Known gaps this month",
      "",
      "- Eleven ketamine entries are missing a second signature.",
      "- Two fentanyl patch placements were logged on the treatment sheet but not in the controlled log.",
      "- The overnight crash cart count was skipped on three evenings.",
      "",
      "## Expected practice going forward",
      "",
      "- Witness signatures are collected at the time of the dose, not at end of shift.",
      "- Cart counts happen at every shift handoff and are initialed by both parties.",
      "- Corrections are struck through with a single line and initialed. No correction fluid, no re-writing a page.",
      "",
      "> [!critical] Discrepancies that cannot be explained are escalated to the Practice Administrator the same day.",
    ].join("\n"),
  },
];

export const STAFF_DIRECTORY: readonly StaffMember[] = [
  {
    id: "c1a7e430-5b96-4d28-8f13-6e2b9d0a7f54",
    system_id: "EH-1042",
    full_name: "Dr. Maya Okonkwo",
    preferred_name: "Dr. Maya",
    pronouns: "she/her",
    title: "Lead Emergency Clinician",
    departments: ["ER", "ICU"],
    email: "m.okonkwo@eastsideemergencyvet.example",
    phone_extension: "4127",
    direct_phone: "(503) 555-0142",
    shift_preference: "Swing",
    shift_rotations: [
      { label: "Swing", days: "Mon – Tue", hours: "15:00 – 01:00" },
      { label: "Swing", days: "alt. Sat", hours: "13:00 – 23:00" },
    ],
    avatar_url: "",
  },
  {
    id: "2f8d5c19-7a34-4e60-b9c7-3d1f8a2e6b90",
    system_id: "EH-1188",
    full_name: "Trevor Lindqvist",
    preferred_name: "Trev",
    pronouns: "he/him",
    title: "ICU Technician II",
    departments: ["ICU"],
    email: "t.lindqvist@eastsideemergencyvet.example",
    phone_extension: "4310",
    direct_phone: "(503) 555-0177",
    shift_preference: "Overnight",
    shift_rotations: [{ label: "Overnight", days: "Wed – Fri", hours: "23:00 – 09:00" }],
    avatar_url: "",
  },
  {
    id: "8e3c61d4-0b72-4a89-9f26-5c4d7b1e3a05",
    system_id: "EH-1097",
    full_name: "Dana Whitfield",
    preferred_name: "Dana",
    pronouns: "she/her",
    title: "Facilities & Safety Officer",
    departments: ["ER"],
    email: "d.whitfield@eastsideemergencyvet.example",
    phone_extension: "4088",
    direct_phone: "(503) 555-0163",
    shift_preference: "Day",
    shift_rotations: [{ label: "Day", days: "Mon – Fri", hours: "07:00 – 15:00" }],
    avatar_url: "",
  },
  {
    id: "b0f47a92-3d18-4c65-8a2e-9f6b1c8d5e70",
    system_id: "EH-1103",
    full_name: "Dr. Ilan Weiss",
    preferred_name: "Ilan",
    pronouns: "he/him",
    title: "Cardiology Consultant",
    departments: ["Cardiology", "ER"],
    email: "i.weiss@eastsideemergencyvet.example",
    phone_extension: "4205",
    direct_phone: "(503) 555-0181",
    shift_preference: "Day",
    shift_rotations: [
      { label: "Day", days: "Tue – Thu", hours: "08:00 – 18:00" },
      { label: "Day", days: "alt. Fri", hours: "08:00 – 14:00" },
    ],
    avatar_url: "",
  },
  {
    id: "6d92e5b1-7f04-4a38-9c51-2e8a0b3d7f16",
    system_id: "EH-1204",
    full_name: "Dr. Sofia Almeida",
    preferred_name: "Sofia",
    pronouns: "she/her",
    title: "Medical Oncologist",
    departments: ["Oncology", "ICU"],
    email: "s.almeida@eastsideemergencyvet.example",
    phone_extension: "4359",
    direct_phone: "(503) 555-0194",
    shift_preference: "Day",
    shift_rotations: [{ label: "Day", days: "Mon, Wed, Fri", hours: "09:00 – 17:00" }],
    avatar_url: "",
  },
  {
    id: "9a15c807-4b62-4e73-8d29-6c0f3a5b1e84",
    system_id: "EH-1081",
    full_name: "Marcus Oyelaran",
    preferred_name: "Marc",
    pronouns: "he/him",
    title: "Diagnostic Imaging Lead",
    departments: ["Radiology"],
    email: "m.oyelaran@eastsideemergencyvet.example",
    phone_extension: "4266",
    direct_phone: "(503) 555-0128",
    shift_preference: "Day",
    shift_rotations: [{ label: "Day", days: "Mon – Thu", hours: "06:30 – 16:30" }],
    avatar_url: "",
  },
  {
    id: "3c6f8e25-1a97-4d40-b8c3-7e5a9f2d6b01",
    system_id: "EH-1150",
    full_name: "Dr. Hannah Berglund",
    preferred_name: "Hannah",
    pronouns: "they/them",
    title: "Rehabilitation & Exotics Specialist",
    departments: ["Pain Management/Rehabilitation", "Exotics"],
    email: "h.berglund@eastsideemergencyvet.example",
    phone_extension: "4173",
    direct_phone: "(503) 555-0155",
    shift_preference: "Day",
    shift_rotations: [
      { label: "Day", days: "Wed – Thu", hours: "09:00 – 19:00" },
      { label: "Day", days: "alt. Sat", hours: "09:00 – 13:00" },
    ],
    avatar_url: "",
  },
  {
    id: "5a02b7f8-9e61-4c35-8d4f-1b7e0c3a9d28",
    system_id: "EH-0917",
    full_name: "Priya Raghunathan",
    preferred_name: "Priya",
    pronouns: "she/her",
    title: "Client Experience Coordinator",
    departments: ["CSR", "Finance"],
    email: "p.raghunathan@eastsideemergencyvet.example",
    phone_extension: "4021",
    direct_phone: "(503) 555-0109",
    shift_preference: "Day",
    shift_rotations: [{ label: "Day", days: "Mon – Fri", hours: "08:00 – 16:00" }],
    avatar_url: "",
  },
  {
    id: "f7b3d048-2c85-4a19-96e7-4d1b8a0c5f32",
    system_id: "EH-0855",
    full_name: "Nadia Fournier",
    preferred_name: "Nadia",
    pronouns: "she/her",
    title: "Practice Finance Manager",
    departments: ["Finance"],
    email: "n.fournier@eastsideemergencyvet.example",
    phone_extension: "4095",
    direct_phone: "(503) 555-0136",
    shift_preference: "Day",
    shift_rotations: [{ label: "Day", days: "Mon – Fri", hours: "07:30 – 15:30" }],
    avatar_url: "",
  },
];

/** Resolve the SOP a bulletin points at, if any. */
export function findLinkedArticle(bulletin: Bulletin): KnowledgeArticle | null {
  if (!bulletin.linked_sop_id) return null;
  return KNOWLEDGE_ARTICLES.find((article) => article.id === bulletin.linked_sop_id) ?? null;
}

/** Case-insensitive substring match across the searchable fields of an item. */
export function matchesQuery(query: string, fields: readonly (string | undefined)[]): boolean {
  const needle = query.trim().toLowerCase();
  if (needle.length === 0) return true;
  return fields.some((field) => (field ?? "").toLowerCase().includes(needle));
}

/**
 * `"All"` matches everything; otherwise the record must carry the department in
 * its multi-tag array.
 */
export function matchesDepartment(tags: readonly ClinicalDepartment[], active: Department): boolean {
  return active === "All" || tags.includes(active);
}